[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient
    miguelbalboa/MFRC522@^1.4.11
    madhephaestus/ESP32Servo@^3.0.6